apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-defrag
  namespace: kube-system
spec:
  schedule: "14 9 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcd-defrag
            image: ghcr.io/ahrtr/etcd-defrag:v0.4.0
            args:
            - --endpoints=https://127.0.0.1:2379
            - --cacert=/etc/kubernetes/pki/etcd/ca.crt
            - --cert=/etc/kubernetes/pki/etcd/peer.crt
            - --key=/etc/kubernetes/pki/etcd/peer.key
            - --cluster
            - --defrag-rule
            - "dbQuotaUsage > 0.8 || dbSize - dbSizeInUse > 200*1024*1024"
            volumeMounts:
            - mountPath: /etc/kubernetes/pki/etcd
              name: etcd-certs
          volumes:
          - hostPath:
              path: /etc/kubernetes/pki/etcd
              type: Directory
            name: etcd-certs
          restartPolicy: OnFailure
          hostNetwork: true # needed in order to reach the etcd server with 127.0.0.1:2379
          securityContext:
            runAsUser: 0
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          - effect: NoExecute
            operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
